"""remove project_id from meaning_maps

Revision ID: 24dc98b94ae1
Revises: e8d6b0446bcf
Create Date: 2026-03-03 20:45:38.889075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24dc98b94ae1'
down_revision: Union[str, None] = 'e8d6b0446bcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_meaning_maps_project_id', table_name='meaning_maps')
    op.drop_constraint('meaning_maps_project_id_fkey', 'meaning_maps', type_='foreignkey')
    op.drop_column('meaning_maps', 'project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meaning_maps', sa.Column('project_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.create_foreign_key('meaning_maps_project_id_fkey', 'meaning_maps', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_meaning_maps_project_id', 'meaning_maps', ['project_id'], unique=False)
    # ### end Alembic commands ###
