"""add_meaning_map_tables

Revision ID: e8d6b0446bcf
Revises: 20260227_0005
Create Date: 2026-03-03 16:41:14.868180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8d6b0446bcf'
down_revision: Union[str, None] = '20260227_0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bible_books',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('abbreviation', sa.String(length=20), nullable=False),
    sa.Column('testament', sa.Enum('OT', 'NT', name='testament_enum'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('chapter_count', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pericopes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_start', sa.Integer(), nullable=False),
    sa.Column('verse_start', sa.Integer(), nullable=False),
    sa.Column('chapter_end', sa.Integer(), nullable=False),
    sa.Column('verse_end', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['bible_books.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pericopes_book_id'), 'pericopes', ['book_id'], unique=False)
    op.create_table('meaning_maps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pericope_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('analyst_id', sa.String(length=36), nullable=False),
    sa.Column('cross_checker_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'CROSS_CHECK', 'APPROVED', name='meaning_map_status_enum'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('locked_by', sa.String(length=36), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_approved', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analyst_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cross_checker_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pericope_id'], ['pericopes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meaning_maps_analyst_id'), 'meaning_maps', ['analyst_id'], unique=False)
    op.create_index(op.f('ix_meaning_maps_pericope_id'), 'meaning_maps', ['pericope_id'], unique=False)
    op.create_index(op.f('ix_meaning_maps_project_id'), 'meaning_maps', ['project_id'], unique=False)
    op.create_table('meaning_map_feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meaning_map_id', sa.String(length=36), nullable=False),
    sa.Column('section_key', sa.String(length=100), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['meaning_map_id'], ['meaning_maps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meaning_map_feedback_meaning_map_id'), 'meaning_map_feedback', ['meaning_map_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meaning_map_feedback_meaning_map_id'), table_name='meaning_map_feedback')
    op.drop_table('meaning_map_feedback')
    op.drop_index(op.f('ix_meaning_maps_project_id'), table_name='meaning_maps')
    op.drop_index(op.f('ix_meaning_maps_pericope_id'), table_name='meaning_maps')
    op.drop_index(op.f('ix_meaning_maps_analyst_id'), table_name='meaning_maps')
    op.drop_table('meaning_maps')
    op.drop_index(op.f('ix_pericopes_book_id'), table_name='pericopes')
    op.drop_table('pericopes')
    op.drop_table('bible_books')
    # ### end Alembic commands ###
